Pairs:
  data_path: 'data/raw'
  max_time_delta: 30
Vocab:
  size: 5000
  max_seq_length: 64
Model:
  embedding_size: 64
  cell_size: 64
Training:
  epochs: 40
  batch_size: 64
Evaluation:
  run_name: 'latest'